name: dbt_ci_dev

on:
  push:
    branches:
      - dev

jobs:
  run_dbt_test:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.9'

          - name: Install dependencies
            run: pip install dbt-snowflake

          - name: Run dbt
            working-directory: ./brazil_orders_pipeline # <--- Adapte si ton projet est dans un sous-dossier
            env:
              SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
              SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
              SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
              SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
              SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
              SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
            run: |
              dbt deps --profiles-dir .
              dbt build --target ci --profiles-dir .